"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-07-29 22:46:26.337309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_uz', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('name_native', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(length=16), nullable=True),
    sa.Column('supports_tts', sa.Boolean(), nullable=False),
    sa.Column('supports_detection', sa.Boolean(), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_languages_is_active'), 'languages', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('telegram_lang', sa.String(length=10), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin', 'owner')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active', 'blocked_bot', 'banned', 'deleted')", name='ck_users_status'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_referred_by'), 'users', ['referred_by'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('admin_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("mode IN ('copy', 'forward')", name='ck_broadcasts_mode'),
    sa.CheckConstraint("status IN ('created', 'running', 'cancel_requested', 'cancelled', 'completed', 'failed')", name='ck_broadcasts_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_created_by'), 'broadcasts', ['created_by'], unique=False)
    op.create_index(op.f('ix_broadcasts_status'), 'broadcasts', ['status'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=False),
    sa.Column('button_text', sa.String(length=255), nullable=False),
    sa.Column('button_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('channel_username')
    )
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_index(op.f('ix_chats_is_active'), 'chats', ['is_active'], unique=False)
    op.create_table('daily_usage',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('translations_count', sa.Integer(), nullable=False),
    sa.Column('tts_count', sa.Integer(), nullable=False),
    sa.Column('chars_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_index('idx_daily_usage_date', 'daily_usage', ['date'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('bot', 'admin', 'system', 'webhook')", name='ck_events_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_created_brin', 'events', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_events_payload', 'events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('idx_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('input_kind', sa.String(length=20), nullable=False),
    sa.Column('source_lang_requested', sa.String(length=10), nullable=False),
    sa.Column('source_lang_detected', sa.String(length=10), nullable=True),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('source_chars', sa.Integer(), nullable=False),
    sa.Column('target_chars', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("chat_type IN ('private', 'group', 'supergroup', 'channel', 'inline')", name='ck_translations_chat_type'),
    sa.CheckConstraint("input_kind IN ('text', 'voice', 'photo', 'document', 'forward', 'inline')", name='ck_translations_input_kind'),
    sa.CheckConstraint("status IN ('success', 'error', 'timeout')", name='ck_translations_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_translations_created_brin', 'translations', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_translations_failures', 'translations', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status <> 'success'"))
    op.create_index('idx_translations_lang_pair', 'translations', ['source_lang_detected', 'target_lang'], unique=False)
    op.create_index('idx_translations_user_created', 'translations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_translations_source_hash'), 'translations', ['source_hash'], unique=False)
    op.create_index(op.f('ix_translations_user_id'), 'translations', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('interface_lang', sa.String(length=10), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_auto', sa.Boolean(), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=True),
    sa.Column('save_history', sa.Boolean(), nullable=False),
    sa.Column('allow_training', sa.Boolean(), nullable=False),
    sa.Column('daily_limit_override', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_allow_training'), 'user_settings', ['allow_training'], unique=False)
    op.create_table('broadcast_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('delivered', 'failed', 'blocked', 'skipped')", name='ck_deliveries_status'),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_deliveries_broadcast_id'), 'broadcast_deliveries', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_user_id'), 'broadcast_deliveries', ['user_id'], unique=False)
    op.create_table('translation_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('translation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('signal', sa.String(length=32), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("signal IN ('copied', 'tts_played', 'favorited', 'unfavorited', 'retranslated', 'lang_switched_after', 'reported', 'corrected')", name='ck_signals_signal'),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_type_created', 'translation_signals', ['signal', 'created_at'], unique=False)
    op.create_index(op.f('ix_translation_signals_translation_id'), 'translation_signals', ['translation_id'], unique=False)
    op.create_index(op.f('ix_translation_signals_user_id'), 'translation_signals', ['user_id'], unique=False)
    op.create_table('tts_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('translation_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('voice', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('success', 'error', 'timeout')", name='ck_tts_status'),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_requests_text_hash'), 'tts_requests', ['text_hash'], unique=False)
    op.create_index(op.f('ix_tts_requests_user_id'), 'tts_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_requests_user_id'), table_name='tts_requests')
    op.drop_index(op.f('ix_tts_requests_text_hash'), table_name='tts_requests')
    op.drop_table('tts_requests')
    op.drop_index(op.f('ix_translation_signals_user_id'), table_name='translation_signals')
    op.drop_index(op.f('ix_translation_signals_translation_id'), table_name='translation_signals')
    op.drop_index('idx_signals_type_created', table_name='translation_signals')
    op.drop_table('translation_signals')
    op.drop_index(op.f('ix_broadcast_deliveries_user_id'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcast_deliveries_broadcast_id'), table_name='broadcast_deliveries')
    op.drop_table('broadcast_deliveries')
    op.drop_index(op.f('ix_user_settings_allow_training'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_translations_user_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_source_hash'), table_name='translations')
    op.drop_index('idx_translations_user_created', table_name='translations')
    op.drop_index('idx_translations_lang_pair', table_name='translations')
    op.drop_index('idx_translations_failures', table_name='translations', postgresql_where=sa.text("status <> 'success'"))
    op.drop_index('idx_translations_created_brin', table_name='translations', postgresql_using='brin')
    op.drop_table('translations')
    op.drop_index('idx_events_user_created', table_name='events')
    op.drop_index('idx_events_type_created', table_name='events')
    op.drop_index('idx_events_payload', table_name='events', postgresql_using='gin')
    op.drop_index('idx_events_created_brin', table_name='events', postgresql_using='brin')
    op.drop_table('events')
    op.drop_index('idx_daily_usage_date', table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_chats_is_active'), table_name='chats')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_broadcasts_status'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_created_by'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_is_active'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
